universe = vanilla
log = submit_$(param)_$(func).log
error = submit_$(param)_$(func).err

executable = run_python.sh
arguments = $(param) $(func)
output = submit_$(param)_$(func).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = sub_files/python.tar.gz, sub_files/small_trainset.pkl, sub_files/tools.py

request_cpus = 4 
request_memory = 1GB
# existing trainset is only 2MB, the other one is 14 MB
request_disk = 10MB

queue param, func from param_func.txt
