universe = vanilla
log = submit_$(param)_$(func).log
error = submit_$(param)_$(func).err
output = submit_$(param)_$(func).out

requirements = (OpSysMajorVer == 7)
executable = run_python.sh
arguments = $(param) $(func)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = python.tar.gz, small_trainset.pkl, tools.py

request_cpus = 4
request_memory = 1GB
request_disk = 10MB

queue param,func from param_func.txt
